/**
 * @module lib/top1000-tickers
 * @description Curated universe of US company tickers StockHuntr tracks (filings RSS filter).
 *
 * EXPORTS:
 * - TOP_1000_TICKERS (const) - Array of unique, currently-listed US ticker symbols.
 *
 * MAINTENANCE:
 * - Reconciled 2026-08-15: deduplicated, removed delisted/acquired
 *   companies (validated against SEC filer list + recent filing activity), and added
 *   companies already tracked in the database. Regenerate via scripts reconciliation.
 * - Class shares use dot notation (e.g. BRK.B). Some DB tickers use hyphen (BF-B).
 */

export const TOP_1000_TICKERS = [
  'AAPL', 'MSFT', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK.B', 'LLY', 'V',
  'WMT', 'JPM', 'XOM', 'UNH', 'MA', 'JNJ', 'PG', 'AVGO', 'HD', 'CVX',
  'MRK', 'COST', 'ABBV', 'BAC', 'KO', 'ORCL', 'PEP', 'CRM', 'TMO', 'CSCO',
  'ACN', 'MCD', 'ADBE', 'ABT', 'LIN', 'NKE', 'DIS', 'AMD', 'WFC', 'TXN',
  'NFLX', 'PM', 'DHR', 'VZ', 'INTU', 'QCOM', 'IBM', 'AMGN', 'RTX', 'NEE',
  'UPS', 'LOW', 'HON', 'SPGI', 'PFE', 'CAT', 'AMAT', 'GE', 'T', 'MS',
  'UNP', 'ELV', 'BLK', 'SYK', 'AXP', 'BKNG', 'DE', 'SCHW', 'TJX', 'MDLZ',
  'GILD', 'VRTX', 'MMC', 'C', 'ADI', 'LRCX', 'PLD', 'ADP', 'SBUX', 'CI',
  'ZTS', 'REGN', 'TMUS', 'BMY', 'NOW', 'MO', 'AMT', 'SO', 'ISRG', 'CB',
  'BDX', 'DUK', 'SLB', 'PYPL', 'PGR', 'ETN', 'GS', 'APD', 'MU', 'CVS',
  'TGT', 'CL', 'SHW', 'EQIX', 'ITW', 'NOC', 'BSX', 'CME', 'USB', 'EMR',
  'MMM', 'NSC', 'MCO', 'CSX', 'WM', 'ICE', 'AON', 'COP', 'TT', 'EW',
  'FDX', 'GD', 'FCX', 'PSA', 'D', 'ECL', 'MCK', 'HCA', 'ORLY', 'MAR',
  'AJG', 'ROP', 'APH', 'HUM', 'NXPI', 'KLAC', 'AFL', 'CARR', 'MSI', 'SRE',
  'MNST', 'TFC', 'GM', 'PCAR', 'CMG', 'O', 'AIG', 'HLT', 'MSCI', 'AEP',
  'JCI', 'F', 'PSX', 'MCHP', 'AZO', 'APO', 'ADSK', 'SYY', 'MET', 'TRV',
  'PAYX', 'KMB', 'EXC', 'DLR', 'DOW', 'VLO', 'WELL', 'TEL', 'ALL', 'FTNT',
  'EA', 'BK', 'WMB', 'KMI', 'CDNS', 'ROST', 'DHI', 'LHX', 'IQV', 'PRU',
  'IDXX', 'PH', 'DD', 'GIS', 'CCI', 'CTAS', 'YUM', 'OKE', 'SPG', 'RSG',
  'CTVA', 'NEM', 'HSY', 'BIIB', 'DXCM', 'ED', 'CMI', 'CPRT', 'KR', 'SNPS',
  'EXR', 'A', 'KVUE', 'AMP', 'GPN', 'ODFL', 'FAST', 'VRSK', 'LEN', 'XEL',
  'CHTR', 'AXON', 'FICO', 'TTWO', 'PCG', 'CEG', 'KHC', 'IRM', 'IT', 'CTSH',
  'DAL', 'GLW', 'VICI', 'IR', 'HWM', 'OTIS', 'WAB', 'GEHC', 'ACGL', 'VMC',
  'MLM', 'MTD', 'STZ', 'RMD', 'CBRE', 'URI', 'PPG', 'NDAQ', 'WEC', 'PWR',
  'FTV', 'FANG', 'EIX', 'HIG', 'ROK', 'WBD', 'AVB', 'KEYS', 'FITB', 'ILMN',
  'EQR', 'DOV', 'HBAN', 'HPQ', 'DTE', 'RJF', 'MTB', 'WY', 'SBAC', 'ETR',
  'AWK', 'NTRS', 'FE', 'EFX', 'PPL', 'STT', 'HPE', 'ADM', 'IFF', 'BALL',
  'LVS', 'PTC', 'CFG', 'K', 'INVH', 'RF', 'CTRA', 'EPAM', 'TDY', 'AEE',
  'CAH', 'DRI', 'HOLX', 'ESS', 'MAA', 'WAT', 'CLX', 'NTAP', 'HUBB', 'BRO',
  'SWK', 'CNP', 'LUV', 'ALGN', 'FDS', 'TSN', 'TROW', 'STLD', 'TYL', 'DGX',
  'VLTO', 'CINF', 'MKC', 'KIM', 'VTR', 'GWW', 'EXPD', 'VRSN', 'EXPE', 'CMS',
  'LDOS', 'APTV', 'MTCH', 'BLDR', 'CDW', 'TER', 'J', 'ARE', 'JKHY', 'LYB',
  'COF', 'AKAM', 'SWKS', 'INCY', 'NVR', 'STE', 'LH', 'BBY', 'BAX', 'NI',
  'TXT', 'PAYC', 'CBOE', 'TECH', 'LNT', 'REG', 'ZBRA', 'IP', 'MOH',
  'ATO', 'EBAY', 'WDC', 'EVRG', 'JBHT', 'POOL', 'UDR', 'AMCR', 'IEX', 'CAG',
  'OMC', 'GPC', 'HST', 'FFIV', 'MAS', 'PNR', 'CHRW', 'SYF', 'ULTA', 'CE',
  'NRG', 'CPT', 'BXP', 'NDSN', 'BEN', 'CPB', 'HRL', 'DPZ', 'AIZ', 'WHR',
  'TRGP', 'PNW', 'PKG', 'LKQ', 'TPR', 'KMX', 'HSIC', 'RHI', 'SNA', 'EMN',
  'MKTX', 'ALLE', 'GNRC', 'IPG', 'HII', 'TAP', 'CRL', 'WRB', 'VTRS', 'MOS',
  'ZION', 'AOS', 'AAL', 'SEE', 'BWA', 'WYNN', 'MGM', 'DVA', 'ALB', 'ROL',
  'APA', 'OVV', 'ENPH', 'GL', 'HAS', 'UAL', 'NCLH', 'CCL', 'RCL',
  'CZR', 'BBWI', 'RL', 'HBI', 'PVH', 'UAA', 'NWS', 'FOX', 'AAP', 'LEG',
  'PARA', 'VFC', 'FRT', 'ACI', 'KSS', 'DXC', 'NWL', 'IVZ', 'NAVI', 'OGN',
  'XRAY', 'FMC', 'BIO', 'JBLU', 'ALK', 'PENN', 'BYD', 'FNF', 'WU', 'HRB',
  'RRX', 'PB', 'CMA', 'SJM', 'CPRI', 'MHK', 'IPGP', 'CNX', 'AR',
  'CIEN', 'SNV', 'LUMN', 'AIV', 'MAT', 'FLR', 'CF', 'AES', 'AVY', 'BKR',
  'MUR', 'DVN', 'EOG', 'NOV', 'NBR', 'RRC', 'MTDR', 'OXY', 'APC', 'NFE',
  'CVE', 'GPOR', 'HP', 'HLX', 'PR', 'MGY', 'CHRD', 'SM', 'NOG', 'NEXT',
  'RNGR', 'REI', 'CRK', 'CRGY', 'CAKE', 'TXRH', 'BLMN', 'WEN', 'JACK', 'PZZA',
  'DIN', 'BJRI', 'PLAY', 'EAT', 'TACO', 'BROS', 'SHAK', 'WING', 'NDLS', 'CBRL',
  'KRUS', 'NGVC', 'IMKTA', 'VLGEA', 'THS', 'CHEF', 'DENN', 'LOCO', 'FWRD', 'WGO',
  'THO', 'CWH', 'PATK', 'LCII', 'WNC', 'MBUU', 'GIII', 'LE', 'TLYS', 'SCVL',
  'CTRN', 'SHOO', 'CAL', 'EBF', 'GES', 'BOOT', 'KIRK', 'DBI', 'ABM', 'BRC',
  'GEO', 'CXW', 'TNC', 'NPO', 'ARES', 'APG', 'MTZ', 'MGPI', 'SAM', 'WEST',
  'ABCB', 'BANF', 'CBSH', 'CFR', 'WTFC', 'UMBF', 'ONB', 'TCBI', 'UCB', 'CVBF',
  'UBSI', 'FULT', 'FNB', 'FIBK', 'INDB', 'NBTB', 'PFS', 'SBCF', 'THFF', 'TRMK', 'WASH', 'WABC', 'WRLD', 'WSFS', 'BANC', 'BOH', 'BKU', 'CATY',
  'CBU', 'FFBC', 'FFIN', 'FISI', 'FRME', 'FSBW', 'HBT', 'HOPE', 'PNFP',
  'SFBS', 'SFNC', 'SBSI', 'SSB', 'WAFD', 'APAM', 'JHG', 'SEIC', 'AMG', 'VOYA',
  'SI', 'SF', 'HLNE', 'JXN', 'RGA', 'FG', 'KMPR', 'RYAN', 'GSHD', 'RNR',
  'THG', 'AXS', 'KNSL', 'PRI', 'ORI', 'RLI', 'SIGI', 'AFG', 'UFCS', 'NJR',
  'SR', 'ALE', 'AVA', 'BKH', 'CPK', 'MDU', 'NWE', 'OGE', 'OGS', 'POR',
  'SWX', 'UTL', 'ES', 'PEG', 'VST', 'IDA', 'UGI', 'NWN', 'SJW', 'YORW',
  'AWR', 'CWT', 'MSEX', 'ARTNA', 'WTRG', 'BIPC', 'BIP', 'BEPC', 'BEP', 'AQN',
  'CWEN', 'AA', 'ABNB', 'ACM', 'AIT', 'ALLY', 'AME', 'AMH', 'AMKR', 'ANET',
  'APP', 'ARM', 'ARMK', 'ASML', 'ATI', 'AVAV', 'AYI', 'AZN', 'BA', 'BF-B',
  'BG', 'BJ', 'BMRN', 'BR', 'BSY', 'BURL', 'BWXT', 'BX', 'CACI',
  'CART', 'CASY', 'CCEP', 'CCK', 'CELH', 'CG', 'CHD', 'CHWY', 'CLH', 'CMCSA',
  'CNC', 'CNH', 'CNM', 'COHR', 'COIN', 'COKE', 'COO', 'COR', 'CPAY', 'CR',
  'CRS', 'CRWD', 'CSGP', 'CSL', 'CW', 'DASH', 'DAY', 'DCI', 'DDOG', 'DECK',
  'DELL', 'DG', 'DKS', 'DLTR', 'DOC', 'DOCU', 'DT', 'DTM', 'EG', 'EHC',
  'EL', 'ELAN', 'ELS', 'EME', 'ENSG', 'ENTG', 'EQH', 'EQT', 'ERIE', 'EVR',
  'EWBC', 'EXE', 'EXEL', 'FHN', 'FI', 'FIS', 'FIX', 'FLEX', 'FN',
  'FSLR', 'FTI', 'GAP', 'GDDY', 'GEN', 'GEV', 'GFS', 'GGG', 'GLPI', 'GME',
  'GMED', 'GOOG', 'GRMN', 'GWRE', 'H', 'HAL', 'HLI', 'HOOD', 'IBKR', 'INTC',
  'ITT', 'JAZZ', 'JBL', 'JEF', 'JLL', 'KDP', 'KEY', 'KKR', 'KTOS', 'L',
  'LAMR', 'LECO', 'LII', 'LITE', 'LMT', 'LSCC', 'LULU', 'LW', 'LYV', 'MANH',
  'MDT', 'MEDP', 'MELI', 'MKSI', 'MLI', 'MP', 'MPC', 'MPWR', 'MRNA', 'MRVL',
  'MSTR', 'MTSI', 'NBIX', 'NLY', 'NTNX', 'NUE', 'NVT', 'NXT', 'NYT', 'OHI',
  'OKTA', 'ON', 'PAG', 'PANW', 'PDD', 'PEGA', 'PEN', 'PFG', 'PFGC', 'PHM',
  'PLTR', 'PNC', 'PODD', 'PSKY', 'Q', 'RBA', 'RBC', 'REXR', 'RGLD',
  'RMBS', 'ROIV', 'RPM', 'RS', 'RVTY', 'SATS', 'SCI', 'SGI', 'SHOP', 'SMCI',
  'SNDK', 'SNX', 'SOLS', 'SOLV', 'STRL', 'STX', 'SW', 'TDG', 'TEAM', 'TFX',
  'THC', 'TKO', 'TLN', 'TOL', 'TPL', 'TRI', 'TRMB', 'TRU', 'TSCO', 'TTD',
  'TWLO', 'UBER', 'UHS', 'UNM', 'USFD', 'UTHR', 'VNOM', 'WBS', 'WCC', 'WDAY',
  'WMG', 'WMS', 'WPC', 'WSM', 'WSO', 'WST', 'WTW', 'WWD', 'XPO', 'XYL',
  'XYZ', 'ZBH', 'ZS'
];
